#[derive(Clone)]
pub enum UserInput {
    SingleClick { key_down: u16, key_up: u16, title: &'static str},
    DoubleClick { key: u16, title: &'static str },
    KeyPress { key: u16, title: &'static str}
}

impl UserInput {
    pub fn get_title(&self) -> &str {
        match self {
            UserInput::SingleClick { title,.. } => title,
            UserInput::DoubleClick { title,.. } => title,
            UserInput::KeyPress { title,..  } => title
        }
    }
}

pub static USER_INPUTS: [UserInput; 78] = [
    UserInput::KeyPress { key: 0x0, title: "" },
    UserInput::KeyPress { key: 0x70, title: "F1" },
    UserInput::KeyPress { key: 0x71, title: "F2" },
    UserInput::KeyPress { key: 0x72, title: "F3" },
    UserInput::KeyPress { key: 0x73, title: "F4" },
    UserInput::KeyPress { key: 0x74, title: "F5" },
    UserInput::KeyPress { key: 0x75, title: "F6" },
    UserInput::KeyPress { key: 0x76, title: "F7" },
    UserInput::KeyPress { key: 0x77, title: "F8" },
    UserInput::KeyPress { key: 0x78, title: "F9" },
    UserInput::KeyPress { key: 0x79, title: "F10" },
    UserInput::KeyPress { key: 0x7A, title: "F11" },
    UserInput::KeyPress { key: 0x7B, title: "F12" },
    UserInput::SingleClick { key_down: 0x0201, key_up: 0x0202, title: "Mouse Sol Tek" },
    UserInput::SingleClick { key_down: 0x0204, key_up: 0x0205, title: "Mouse Sag Tek" },
    UserInput::DoubleClick { key:  0x0203, title: "Mouse Sol Cift" },
    UserInput::DoubleClick { key:  0x0206, title: "Mouse Sag Cift" },
    UserInput::KeyPress { key: 0x30, title: "0" },
    UserInput::KeyPress { key: 0x31, title: "1" },
    UserInput::KeyPress { key: 0x32, title: "2" },
    UserInput::KeyPress { key: 0x33, title: "3" },
    UserInput::KeyPress { key: 0x34, title: "4" },
    UserInput::KeyPress { key: 0x35, title: "5" },
    UserInput::KeyPress { key: 0x36, title: "6" },
    UserInput::KeyPress { key: 0x37, title: "7" },
    UserInput::KeyPress { key: 0x38, title: "8" },
    UserInput::KeyPress { key: 0x39, title: "9" },
    UserInput::KeyPress { key: 0x41, title: "A" },
    UserInput::KeyPress { key: 0x42, title: "B" },
    UserInput::KeyPress { key: 0x43, title: "C" },
    UserInput::KeyPress { key: 0x44, title: "D" },
    UserInput::KeyPress { key: 0x45, title: "E" },
    UserInput::KeyPress { key: 0x46, title: "F" },
    UserInput::KeyPress { key: 0x47, title: "G" },
    UserInput::KeyPress { key: 0x48, title: "H" },
    UserInput::KeyPress { key: 0x49, title: "I" },
    UserInput::KeyPress { key: 0x4A, title: "J" },
    UserInput::KeyPress { key: 0x4B, title: "K" },
    UserInput::KeyPress { key: 0x4C, title: "L" },
    UserInput::KeyPress { key: 0x4D, title: "M" },
    UserInput::KeyPress { key: 0x4E, title: "N" },
    UserInput::KeyPress { key: 0x4F, title: "O" },
    UserInput::KeyPress { key: 0x50, title: "P" },
    UserInput::KeyPress { key: 0x51, title: "Q" },
    UserInput::KeyPress { key: 0x52, title: "R" },
    UserInput::KeyPress { key: 0x53, title: "S" },
    UserInput::KeyPress { key: 0x54, title: "T" },
    UserInput::KeyPress { key: 0x55, title: "U" },
    UserInput::KeyPress { key: 0x56, title: "V" },
    UserInput::KeyPress { key: 0x57, title: "W" },
    UserInput::KeyPress { key: 0x58, title: "X" },
    UserInput::KeyPress { key: 0x59, title: "Y" },
    UserInput::KeyPress { key: 0x5A, title: "Z" },
    UserInput::KeyPress { key: 0x08, title: "Backspace" },
    UserInput::KeyPress { key: 0x09, title: "Tab" },
    UserInput::KeyPress { key: 0x0C, title: "Clear" },
    UserInput::KeyPress { key: 0x0D, title: "Enter" },
    UserInput::KeyPress { key: 0x10, title: "Shift" },
    UserInput::KeyPress { key: 0x11, title: "Ctrl" },
    UserInput::KeyPress { key: 0x12, title: "Alt" },
    UserInput::KeyPress { key: 0x13, title: "Pause" },
    UserInput::KeyPress { key: 0x14, title: "Caps Lock" },
    UserInput::KeyPress { key: 0x1B, title: "Esc" },
    UserInput::KeyPress { key: 0x20, title: "Space" },
    UserInput::KeyPress { key: 0x21, title: "Page Up" },
    UserInput::KeyPress { key: 0x22, title: "Page Down" },
    UserInput::KeyPress { key: 0x23, title: "End" },
    UserInput::KeyPress { key: 0x24, title: "Home" },
    UserInput::KeyPress { key: 0x25, title: "Left Arrow" },
    UserInput::KeyPress { key: 0x26, title: "Up Arrow" },
    UserInput::KeyPress { key: 0x27, title: "Right Arrow" },
    UserInput::KeyPress { key: 0x28, title: "Down Arrow" },
    UserInput::KeyPress { key: 0x29, title: "Select" },
    UserInput::KeyPress { key: 0x2A, title: "Print" },
    UserInput::KeyPress { key: 0x2B, title: "Execute" },
    UserInput::KeyPress { key: 0x2C, title: "Print Screen" },
    UserInput::KeyPress { key: 0x2D, title: "Insert" },
    UserInput::KeyPress { key: 0x2E, title: "Delete" },
];